---
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 5s
scrape_configs:
  - job_name: prometheus
    scheme: http
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: grafana
    scheme: http
    static_configs:
      - targets:
        - grafana:3000
  - job_name: traefik
    scheme: http
    static_configs:
      - targets:
        - traefik:8080
  - job_name: docker
    scheme: http
    static_configs:
      - targets: 
        - 172.17.0.1:9323
  - job_name: nerds
    static_configs:
      - targets:
        - nerds.garflak.com:9100
  - job_name: pihole
    static_configs:
      - targets:
        - pihole.garflak.com:9100